### PR TITLE
This hack enables long queries from notmuch virtual-folders

### LINKED ISSUE #122: is long query in virtual-mailboxes working?
I'm using this:

    mutt-kz-1.5.23.1-2.20150717.git.24c06e70.fc23.x86_64
    notmuch-0.21-1.fc23.x86_64

and in .muttrc I have:

    virtual-mailboxes \
       [...] \
       'UNSORTED'   'notmuch://?query=NOT ( tag:inbox or tag:archive or tag:mailinglist1 or tag:mailinglist2 or [...] )'

The string with query is 511 chars long if there is some limit. I just want folder which would catch all emails not sorted in all other virtual folders.

With this I still see emails tagged with, say, "mailinglist19" in the UNSORTED virtual folder. There is no error printed by mutt.

### PR DESCRIPTION
**Pull request by yeled**
Otherwise, they get cut off at 256 characters.

This fixes #122 and references the patch in aa49858. It should be patched alongside @bami's work as well so the sidebar updates correctly, too (the notmuch `count` and `query` use different queries).

### CODE REVIEW

**Comment by timofonic** [comment]
No merge? :(

**Comment by karelzak** [comment]
Sorry, for delay. I'll merge it after rebase (sync with the current mutt upstream). Thanks!

**Comment by yeled** [comment]
I feel like this has been lost since the mutt-kz/neomutt merging.

**Comment by karelzak** [comment]
@yeled it would be nice to split all the patches to small pull requests, it's really difficult to review and discuss so huge pull request.

**Comment by yeled** [comment]
yeah what has gone wrong here? It's rebased on something else I think (it was a two-patch change).

I'll fix it or resubmit a new one.

**Comment by karelzak** [comment]
@yeled please, please... develop non-notmuch features and bugfix against neomutt project (https://github.com/neomutt/neomutt)

**Pull request closed without merging**
